### ISSUE TITLE
Compilation Errors on Travis (for R package)

### ISSUE THREAD

**Issue by leeper** [wesm/feather#154]
I have an R package that imports feather. Builds on Travis [are failing due feather failing to compile](https://travis-ci.org/leeper/rio/builds/131446802#L1826-L1858). Any ideas how to correct?

Here's the set of errors:

```
* installing *source* package ‘feather’ ...
** package ‘feather’ successfully unpacked and MD5 sums checked
** libs
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -c feather-read.cpp -o feather-read.o
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -c feather-types.cpp -o feather-types.o
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -c feather-write.cpp -o feather-write.o
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -c feather/buffer.cc -o feather/buffer.o
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -c feather/feather-c.cc -o feather/feather-c.o
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -c feather/io.cc -o feather/io.o
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -c feather/metadata.cc -o feather/metadata.o
feather/metadata.cc:29:7: error: expected nested-name-specifier before ‘FBString’
feather/metadata.cc:29:7: error: ‘FBString’ has not been declared
feather/metadata.cc:29:16: error: expected ‘;’ before ‘=’ token
feather/metadata.cc:29:16: error: expected unqualified-id before ‘=’ token
feather/metadata.cc:32:7: error: expected nested-name-specifier before ‘ColumnVector’
feather/metadata.cc:32:7: error: ‘ColumnVector’ has not been declared
feather/metadata.cc:32:20: error: expected ‘;’ before ‘=’ token
feather/metadata.cc:32:20: error: expected unqualified-id before ‘=’ token
feather/metadata.cc:178:3: error: ‘ColumnVector’ does not name a type
feather/metadata.cc: In member function ‘feather::Status feather::metadata::TableBuilder::Impl::Finish()’:
feather/metadata.cc:146:5: error: ‘FBString’ was not declared in this scope
feather/metadata.cc:146:14: error: expected ‘;’ before ‘desc’
feather/metadata.cc:148:7: error: ‘desc’ was not declared in this scope
feather/metadata.cc:154:9: error: ‘desc’ was not declared in this scope
feather/metadata.cc:156:27: error: ‘columns_’ was not declared in this scope
feather/metadata.cc:157:34: error: unable to deduce ‘auto’ from ‘<expression error>’
feather/metadata.cc: In member function ‘void feather::metadata::TableBuilder::Impl::add_column(const flatbuffers::Offset<feather::fbs::Column>&)’:
feather/metadata.cc:173:5: error: ‘columns_’ was not declared in this scope
feather/metadata.cc: In constructor ‘feather::metadata::TableBuilder::TableBuilder()’:
feather/metadata.cc:190:5: error: type ‘feather::metadata::TableBuilder’ is not a direct base of ‘feather::metadata::TableBuilder’
make: *** [feather/metadata.o] Error 1
ERROR: compilation failed for package ‘feather’
* removing ‘/usr/local/lib/R/site-library/feather’
```

**Comment by hadley** [comment]
The problem is `-std=c++0x` - but I don't know why it wouldn't be picking up the `SystemRequirements: C++11`. Any ideas @jimhester ?

**Comment by jimhester** [comment]
I think the problem is the configure file, from https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b11-code

> If a package using C++11 has a configure script it is essential that it selects the correct compiler, via something like

    CXX1X=`"${R_HOME}/bin/R" CMD config CXX1X`
    CXX1XSTD=`"${R_HOME}/bin/R" CMD config CXX1XSTD`
    CXX="$(CXX1X) $(CXX1XSTD)"
    CXXFLAGS=`"${R_HOME}/bin/R" CMD config CXX1XFLAGS`
    AC_LANG(C++)

I am trying to reproduce the error locally and will send a patch

**Comment by jimhester** [comment]
Actually I am mistaken, the gcc on travis is only 4.6.3, so you need to modify your `.travis.yml` to install at least gcc-4.9 in order to have `-std=c++11`

**Comment by jimhester** [comment]
So you have to install gcc-4.9 or greater _and_ set CXX1X, CXX1XSTD in ~/.R/Makevars, e.g.

https://github.com/jimhester/rio/blob/9026180fd731aaed34f21cba3b5e207124618e5b/.travis.yml#L8-L20

Which allows you to build successfully, https://travis-ci.org/leeper/rio/builds/131807863#L1367-L1380

This is pretty painful, but I am not sure what can be done to avoid it unless travis updates their default gcc or ubuntu version...

**Comment by wesm** [comment]
is this resolved?

**Comment by leeper** [comment]
Yes, @jimhester's travis setup worked for me.

**Comment by maxheld83** [comment]
This fix would appear to cause other problems, though I am not sure whether this is actually an issue on `feather`'s end.

Once I add the above fix to my `.travis.yml`, travis fails on installing `readxl`, and doesn't even get to `feather`:

```
Installing readxl (0.1.1) ... 
Error: Command failed (1)

Failed to run system command:

	'/home/travis/R-bin/lib/R/bin/R' --vanilla CMD INSTALL '/tmp/RtmprmuGtQ/readxl' --library='/home/travis/build/maxheld83/goodlife/packrat/lib/x86_64-pc-linux-gnu/3.3.2' --install-tests --no-docs --no-multiarch --no-demo 

The command failed with output:
* installing *source* package 'readxl' ...
** package 'readxl' successfully unpacked and MD5 sums checked
** libs
g++ -I/home/travis/R-bin/lib/R/include -DNDEBUG -Iunix -I. -I/home/travis/R-bin/include -I"/home/travis/build/maxheld83/goodlife/packrat/lib/x86_64-pc-linux-gnu/3.3.2/Rcpp/include"  -DTINYFORMAT_NO_VARIADIC_TEMPLATES -std=c++11 -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
cc1plus: error: unrecognized command line option '-std=c++11'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package 'readxl'
* removing '/home/travis/build/maxheld83/goodlife/packrat/lib/x86_64-pc-linux-gnu/3.3.2/readxl'
Execution halted


The command "R -e "0" --args --bootstrap-packrat" failed and exited with 1 during .

Your build has been stopped.
```

I'm not sure what to do about that, but the problem seems to stem from the commands added as per the above fix.

Here's the complete `.travis.yml`:

```
language: r

sudo: false

install:
  - R -e "0" --args --bootstrap-packrat

warnings_are_errors: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $TRAVIS_BUILD_DIR/packrat/

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

notifications:
  email: false
```

**Comment by jimhester** [comment]
@maxheld83 I think that is actually a bug in readxl. It sets `-std=c++11` for both the C and C++ compilers, which won't work with the older gcc. 

However it should work if you add `CC=gcc-4.9` to your `~/.R/Makevars` as well.

**Comment by maxheld83** [comment]
thanks @jimhester – is this the same issue as https://github.com/hadley/readxl/issues/176 then?

**Comment by maxheld83** [comment]
also here, FYI, just setting `dist=trusty` solves the problem, though I am not sure whether this is recommended. 

```
language: r

sudo: false

dist: trusty

install:
  - R -e "0" --args --bootstrap-packrat

warnings_are_errors: false

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $TRAVIS_BUILD_DIR/packrat/

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

notifications:
  email: false
```
